### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by AlexisJW** [AlexisJW/javascript-group-capstone#21]
Group capstone: set up your Kanban board

Hello,
[The link of the ](https://github.com/AlexisJW/javaScript-group-capstone/projects/1) Kanban board project has been set up and was created by @AlexisJW  and @flemton

God bless you 👍

**Comment by Olamarx** [comment]
Hi @AlexisJW,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights
- Kanbad Board ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] I can see your project tasks total 16, it is required that a team of two should be 15, I would implore you to follow this.
- [ ] I can also see that some projects aren't assigned to any member, I would implore you to assign it to each and every member to know what they are working on.
![image](https://user-images.githubusercontent.com/86200356/217043660-a1d1e2df-7c0f-41af-9551-0ee2559915f6.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by pinkmoon25** [comment]
Hi @AlexisJW and @flemton , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/zwb4AvXN67p6SlvbIW/giphy.gif"/>

## Highlights
Kanban Board Setup :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
